### ISSUE TITLE
I cannot import these packages into flutter project

### ISSUE THREAD

**Issue by joshuajennysibbu** [MapmyIndia/flutter-mapmyindia-gl#1]
import 'package:mapmyindia_gl_example/model/feature_list.dart';
import 'package:mapmyindia_gl_example/place_symbol.dart';
import 'package:mapmyindia_gl_example/samples/add_marker.dart';
import 'package:mapmyindia_gl_example/samples/add_polyline_wdget.dart';
import 'package:mapmyindia_gl_example/samples/camera_feature.dart';
import 'package:mapmyindia_gl_example/samples/current_location_widget.dart';
import 'package:mapmyindia_gl_example/samples/location_camera_option.dart';
import 'package:mapmyindia_gl_example/samples/map_click_event.dart';
import 'package:mapmyindia_gl_example/samples/map_long_click.dart';
import 'package:mapmyindia_gl_example/samples/marker_dragging_widget.dart';
import 'package:mapmyindia_gl_example/utils/color.dart';
import 'package:mapmyindia_gl_example/utils/feature_type.dart';
import 'package:mapmyindia_gl_example/full_map.dart';

**Comment by Saksham66** [comment]
@joshuajennysibbu 
Please try our sample app in flutter:
https://github.com/MapmyIndia/flutter-mapmyindia-gl

**Comment by joshuajennysibbu** [comment]
> @joshuajennysibbu
> Please try our sample app in flutter:
> https://github.com/MapmyIndia/flutter-mapmyindia-gl

Thank for your reply its work...
 But i got another error....


MapmyIndiaMap(  
	initialCameraPosition: CameraPosition(  
	  target: LatLng(25.321684, 82.987289),  
	  zoom: 14.0,  
	),  
	onMapCreated: (map) =>  
	{  
	  mapController = map,
	},
),

I run your sample code..... I get undefined mapController error... even I try datatype with a variable like 'MapmyIndiaMapController mapController = map,'
 name but it does not work for me........
